### ISSUE TITLE
xcore_gradle: The gradle build fails, as org.antlr:antlr-runtime:[3.2.0, 3.2.1) cannot be resolved.

### ISSUE THREAD

**Issue by ledan87** [itemis/itemis-blog#12]
I had the same issue with my own xcore-project, but it can be reproduced here as well:

When I call `./gradlew build`, the Build fails with 

    FAILURE: Build failed with an exception.

     What went wrong:
    Could not resolve all dependencies for         configuration:org.xtext.example.mydsl.model:xtextLanguages
    Could not find any version that matches org.antlr:antlr-runtime:[3.2.0, 3.2.1).
      Versions that do not match:
          3.5.2
          3.5.1
          3.5
          3.5-rc-2
          3.5-rc-1
          + 12 more
      Required by:
          project :org.xtext.example.mydsl.model > org.eclipse.emf:org.eclipse.emf.ecore.xcore:1.10.0

It seems, that gradle is not able to resolve the dependencies to 3.2
When I put the antrl-runtime with version 3.2.0 manually into my nexus-maven-repository, gradle is able to get the dependency, but it fails later with:

    :org.xtext.example.mydsl.model:generateXtext FAILED

    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':org.xtext.example.mydsl.model:generateXtext'.
    > org.eclipse.xtext.xbase.lib.CollectionLiterals.newHashSet()Ljava/util/HashSet;

**Comment by cdietrich** [comment]
The version is here
https://search.maven.org/artifact/org.antlr/antlr-runtime/3.2/jar

Maybe you should run with —refresh-dependencies
Do you have mavenCentral in the repo list for deps and buildscript ?

**Comment by ledan87** [comment]
I've tried `./gradlew clean build --refresh-dependencies`, unfortunately it had no effect. 

I did not change the content of the branch `xcore_gradle`. (Btw, the build.gradle uses jcenter, the artifact is here: https://jcenter.bintray.com/org/antlr/antlr-runtime/3.2/ but it cannot be resolved either)

I downloaded the artifact and pushed it to our nexus maven repository with version number 3.2.0. Than gradle is able to resolve it, but the build does still not work (fails with the second error message above).

**Comment by cdietrich** [comment]
are you sure you use matching xbase, xbase.lib, xcore versions?

**Comment by cdietrich** [comment]
p.s. i checked out xcore_gradle_upgrade_xtext_neu branch and it seems to work

**Comment by ledan87** [comment]
> 
> 
> p.s. i checked out xcore_gradle_upgrade_xtext_neu branch and it seems to work

With the `neu`-branch it works. I did not know this branch exists, I used the link from here: https://blogs.itemis.com/en/using-xtext-with-xcore-and-gradle.

Danke!

**Comment by ledan87** [comment]
Just a follow up:

I managed to get the build of the other project to work as well. The dependency declarations should be adapted to:

       xtextLanguages 'org.antlr:antlr-runtime:3.2'
       xtextLanguages('org.eclipse.emf:org.eclipse.emf.ecore.xcore:1.3.1'){
           exclude group: 'org.antlr', module: 'antlr-runtime'
           exclude group: 'org.eclipse.xtext', module: 'org.eclipse.xtext'
           exclude group: 'org.eclipse.xtext', module: 'org.eclipse.xtext.xbase'
       }
